baseURL                = "https://zewang0217.github.io/"
languageCode           = "zh-cn"
title                  = "Zewang's Blog"
defaultContentLanguage = "zh"
hasCJKLanguage         = true

[pagination]
    pagerSize = 10

[outputs]
    home = ["HTML", "RSS", "JSON"]

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"